import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Button } from "@mui/material";
export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <Button variant='outlined'>Primary</Button>
        <Button color='secondary'>Secondary</Button>
        <Button variant='contained' color='success'>
          Success
        </Button>
        <Button variant='outlined' color='error'>
          Error
        </Button>

        <div className={styles.grid}></div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
