import Head from "next/head";
import styles from "../styles/Home.module.css";
import "react-toastify/dist/ReactToastify.css";
import { Button } from "@mui/material";
import { useState } from "react";
import React from "react";
import { ToastContainer, toast } from "react-toastify";

export default function Home(props) {
  const [email, setEmail] = useState("");
  const [loading, setLoading] = useState(false);
  const notify = () => toast.success("your email has been submitted!");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome</h1>

        <input
          onChange={(text) => {
            setEmail(text.target.value);
            console.log(email);
          }}
          placeholder='enter your email here'
          className='border-2 p-3 border-black rounded-full'
          type='text'
          name=''
          id=''
        />

        <Button
        
        
          className='bg-black p-4 rounded-full mt-6 text-white text-center'
          buttonName = 'Save'
        />
        
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
